### ISSUE TITLE
Usage advice in integration tests

### ISSUE THREAD

**Issue by lonix1** [Zaid-Ajaj/ThrowawayDb#16]
Hi @Zaid-Ajaj, I'm comparing this very nice library to ["Respawn"](https://github.com/jbogard/Respawn). I want to ensure I understand the differences - Respawn deletes data before/after a test run, whereas your library drops the complete database before/after a test run (or the entire test suite). Am I understanding correctly?

Also, I used to use rollback-able transactions in each test but ran into trouble. I'm trying to decide between your way which seems much cleaner, and the Respawn way which seems much faster. Is it simply a matter of speed? When would you advise to use the one or the other?

**Comment by andre-wells** [comment]
Hi @lonix1 

I've made extensive use of ThrowawayDb for my integration tests (had some legacy which didn't play nice with sqlite).

> your library drops the complete database before/after a test run (or the entire test suite). Am I understanding correctly?

Yes, when an instance of `ThrowawayDatabase` is disposed, the DB is dropped.  You can control when this is happening, either by creating a DB for each test or by making the instant part of a test fixture (where one DB is used for many tests).

For my scenarios, we spin up a DB per test, seed it with data and then perform our Act/Asserts.

> Also, I used to use rollback-able transactions in each test but ran into trouble.

Under what conditions where you running your transactions? Running MSSQL? Are you creating a single DB for a suite of tests and rolling back changes at the end of each test to revert to the original state?

Remember that tests are run in parallel so this might be a case of a single database with multiple tests trying to transact across the same DB objects at the same time.

**Comment by lonix1** [comment]
Yes I think that was the issue - it's easy to run into concurrency problems when testing unless one is very careful. Sadly EF is not easy to use in tests.

Since you've used this library for a while, how do you think it compares with Respawn? That library is recommended for speed, and since I have thousands of tests, I use it. But it seems really "dirty" to share anything between tests, which is why I like this library. How do you find it speed-wise?

**Comment by andre-wells** [comment]
You can use the same data store for tests but you need to consider that other tests are making use of the data source and design your tests for that.  A good example of this making use if Azure Table Storage.  I'm not in a position to spin up a new store for every test (or even a suite of tests) so the tests are designed to seed a random ID and then operate with that ID for the duration.  Yea the data store gets filled with junk but it's dedicated for that.

We're using EF Core without issue in our integration tests, creating a DB each time.  A principle is isolation between tests; data is especially seeded for each scenario.

I've never used Respawn but I think it's fine as long as tests are running in a defined sequence (or sequentially). That's as much honest input I can give having never used it 😅

In terms of speed, our integration tests take 10-14sec to complete (and would be lower but our DB init "does things" that we don't want to change just yet) and we execute them in parallel.  I originally wanted to make use of an in-memory database for speed and IO cost ([EF can do that](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.InMemory)) but we needed an actual SQL server to run against (that "does things" thing I mentioned 🙄)

> That library is recommended for speed, and since I have thousands of tests

Remember that integration tests run orders of magnitude longer than unit tests.  You don't need every permutation (that's what our Unit tests are doing instead).  It's more about test coverage. But I don't know the domain you're working on so I could be speaking out of turn.

Via [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0)

> Don't write integration tests for every possible permutation of data and file access with databases and file systems. Regardless of how many places across an app interact with databases and file systems, a focused set of read, write, update, and delete integration tests are usually capable of adequately testing database and file system components. Use unit tests for routine tests of method logic that interact with these components. In unit tests, the use of infrastructure fakes/mocks result in faster test execution.

**Comment by lonix1** [comment]
@andre-wells I'm considering whether to convert a mega suite of tests to use this library, so real-world experience with the library helps - thanks for your advice! :)

**Comment by andre-wells** [comment]
Good luck @lonix1, I hope it works out for you 😄 

If it helps, I [tweeted](https://twitter.com/beardedwells/status/1468928421979844609) a sample of what my tests look like in regards to fixtures etc.  (That's actually how I found your issue; scheduling the post then seeing the issue list in the repo).

@Zaid-Ajaj, maybe you can close this one?

**Comment by Zaid-Ajaj** [comment]
Hi @lonix1 sorry for the late reply. I think @andre-wells pretty much shared the same thoughts I have. ThrowawayDb helps you test your code with a real db. Whether you want to do that per test or share a database across tests, you get to choose that yourself. We have been using it at work writing ~1000 integration and unit tests. It _does_ take more time to run the tests but for us, it is definitely worth it because of how trivial everything becomes: create test db, run migrations, (optionally) seed data then start operating on it. 

To be honest, I don't know a lot about Respawn, haven't used that before.

**Comment by lonix1** [comment]
Thanks Zaid, and thanks for making this library. I'm gonna try it on some tests and if that works well I'll upgrade the others too.

FYI Respawn is really great and amazingly fast - but COMPLETE isolation of tests would give me more comfort, that's why I'm interested in your library.
