### ISSUE TITLE
New feature - Add DB Name prefix

### ISSUE THREAD

**Issue by ppozeti** [Zaid-Ajaj/ThrowawayDb#4]
It would be awesome if we could pass a name prefix instead of using ThrowawayDb.

**Comment by Zaid-Ajaj** [comment]
Hi @ppozeti, this sounds like a nice idea! An optional name parameter for the `Create` function can be easily added. Would you like to give it a try and implement it? PRs are always welcome :pray:

**Comment by ppozeti** [comment]
There you go! #5
